######################## default configuration ####################
baseURL = "https://kids-bible-clubs.github.io/website"
title = "Kid's Bible Clubs"
theme = "kids-bible-clubs-website"
# post pagination
paginate = "10"
# post excerpt
summaryLength = "15"
# disqus short name
#disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true
